### ISSUE TITLE
Skalierung der Lautstärke-Schieber und Regler

### ISSUE THREAD

**Issue by rstockm** [Ultraschall/ultraschall-soundboard#30]
Die Lautstärke-Regler sollten so umgestellt werden, dass sie ein psycho-akkustisches Modell abbilden. Sprich: Regler auf halbe Strecke sorgt für einen wirklich "halb so lauten" Klang. Ist das logarithmisch? Eventuell ist hier mit verschiedenen Kurven zu experimentieren.

**Comment by danlin** [comment]
Ja der ist gerade linear.

**Comment by danlin** [comment]
Done in 4.0
