### ISSUE TITLE
Linux Build failing

### ISSUE THREAD

**Issue by OOTS** [Ultraschall/ultraschall-soundboard#31]
Hi there,

building this under linux required me to change all four copies of the path `Submodules/JUCE/extras/Projucer/Builds/Linux/` (found in `Build/build_linux.sh`) to `Submodules/JUCE/extras/Projucer/Builds/LinuxMakefile`.
See https://github.com/WeAreROLI/JUCE/tree/master/extras/Projucer/Builds .

I don't know if there has been a change to the JUCE repo or whether the `build_linux.sh` script was broken from the very beginning. I also don't know if other code is affected.

Best regards,
OOTS

**Comment by Alkaris** [comment]
Yeah the script paths is all wrong in this script. it would need a complete rewrite with the correct proper directory structures, looks like they forgot the layout of their source files. I did try having a go at correcting the shell script, but the issues lie within the actual source code files themselves.
